version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - app-network

  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    profiles:
      - dev

  # Monitoring stack
  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "8081:8080"
      - "2004:2003"
      - "8125:8125/udp"
    volumes:
      - graphite-data:/opt/graphite/storage
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - app-network
    depends_on:
      - graphite

volumes:
  graphite-data:
  grafana-data:

networks:
  app-network:
    driver: bridge 